-- Add KYC fields to User
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nameVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailChangeCount" INTEGER NOT NULL DEFAULT 0;
